# Generated by Django 6.0.5 on 2026-08-23 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0115_postratamento_data_resposta_and_more'),
        ('agenda', '0005_alter_agendamento_duracao'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='pos_tratamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agendamentos_retorno', to='accounts.postratamento', verbose_name='Pós-Tratamento'),
        ),
    ]
