# Generated by Django 6.0.5 on 2026-09-14 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0006_agendamento_pos_tratamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloqueioAgenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('feriado', 'Feriado'), ('ferias', 'Férias'), ('ausencia', 'Ausência do profissional'), ('almoco', 'Horário de almoço'), ('manual', 'Bloqueio manual'), ('manutencao', 'Manutenção'), ('outro', 'Outro')], default='manual', max_length=30, verbose_name='Tipo de bloqueio')),
                ('data_inicio', models.DateField(verbose_name='Data inicial')),
                ('data_fim', models.DateField(verbose_name='Data final')),
                ('hora_inicio', models.TimeField(blank=True, null=True, verbose_name='Hora inicial')),
                ('hora_fim', models.TimeField(blank=True, null=True, verbose_name='Hora final')),
                ('descricao', models.CharField(blank=True, max_length=255, null=True, verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('profissional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bloqueios_agenda', to='agenda.profissional', verbose_name='Profissional')),
            ],
            options={
                'verbose_name': 'Bloqueio da Agenda',
                'verbose_name_plural': 'Bloqueios da Agenda',
                'ordering': ['data_inicio', 'hora_inicio'],
            },
        ),
    ]
