# Generated by Django 6.0.5 on 2026-09-15 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0007_bloqueioagenda'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloqueioagenda',
            name='chave_feriado',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Chave do feriado'),
        ),
        migrations.AddField(
            model_name='bloqueioagenda',
            name='origem',
            field=models.CharField(choices=[('manual', 'Cadastro manual'), ('nacional', 'Calendário nacional'), ('estadual', 'Calendário estadual'), ('municipal', 'Calendário municipal')], default='manual', max_length=20, verbose_name='Origem'),
        ),
    ]
