# Generated by Django 6.0.5 on 2026-09-16 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0009_consultorio_agendamento_consultorio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Consultorio',
        ),
    ]
