# Generated by Django 6.0.5 on 2026-08-21 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0111_remove_itemorcamento_posicao_dente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contapagar',
            name='forma_pagamento',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='contapagar',
            name='parcela',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='contapagar',
            name='total_parcelas',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
