# Generated by Django 6.0.5 on 2026-08-21 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0112_contapagar_forma_pagamento_contapagar_parcela_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='entrada',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='compra',
            name='forma_pagamento',
            field=models.CharField(choices=[('DINHEIRO', 'Dinheiro'), ('PIX', 'PIX'), ('DEBITO', 'Cartão de Débito'), ('CREDITO', 'Cartão de Crédito'), ('BOLETO', 'Boleto'), ('TRANSFERENCIA', 'Transferência Bancária'), ('CHEQUE', 'Cheque'), ('OUTRO', 'Outro')], default='PIX', max_length=30),
        ),
        migrations.AddField(
            model_name='compra',
            name='parcelas',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='compra',
            name='primeiro_vencimento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
