# Generated by Django 6.0.5 on 2026-08-22 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0113_compra_entrada_compra_forma_pagamento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PosTratamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_agradecimento', models.CharField(choices=[('PENDENTE', 'Pendente'), ('ENVIADO', 'Enviado')], default='PENDENTE', max_length=15, verbose_name='Status do agradecimento')),
                ('data_agradecimento', models.DateField(blank=True, null=True, verbose_name='Data do agradecimento')),
                ('status_pesquisa', models.CharField(choices=[('PENDENTE', 'Pendente'), ('ENVIADA', 'Enviada'), ('RESPONDIDA', 'Respondida')], default='PENDENTE', max_length=15, verbose_name='Status da pesquisa')),
                ('data_pesquisa', models.DateField(blank=True, null=True, verbose_name='Data da pesquisa')),
                ('nota_satisfacao', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Nota de satisfação')),
                ('comentario_pesquisa', models.TextField(blank=True, verbose_name='Comentário da pesquisa')),
                ('intervalo_retorno', models.PositiveSmallIntegerField(choices=[(3, '3 meses'), (6, '6 meses'), (12, '12 meses')], default=6, verbose_name='Intervalo para retorno')),
                ('data_retorno', models.DateField(blank=True, null=True, verbose_name='Data prevista para retorno')),
                ('status_retorno', models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONTATADO', 'Contatado'), ('AGENDADO', 'Agendado'), ('REALIZADO', 'Realizado')], default='PENDENTE', max_length=15, verbose_name='Status do retorno')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('tratamento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pos_tratamento', to='accounts.tratamento')),
            ],
            options={
                'verbose_name': 'Pós-Tratamento',
                'verbose_name_plural': 'Pós-Tratamentos',
                'ordering': ['-criado_em'],
            },
        ),
    ]
