# Generated by Django 6.0.5 on 2026-08-22 16:13

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0114_postratamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='postratamento',
            name='data_resposta',
            field=models.DateField(blank=True, null=True, verbose_name='Data da resposta'),
        ),
        migrations.AddField(
            model_name='postratamento',
            name='token_pesquisa',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Token da pesquisa'),
        ),
        migrations.AlterField(
            model_name='postratamento',
            name='nota_satisfacao',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Nota de satisfação'),
        ),
    ]
