# Generated by Django 6.0.5 on 2026-08-26 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0115_postratamento_data_resposta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='paciente',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lead_marketing', to='accounts.paciente'),
        ),
    ]
