# Generated by Django 6.0.5 on 2026-08-28 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0116_lead_paciente'),
    ]

    operations = [
        migrations.CreateModel(
            name='CondicaoOdontologica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dente', models.CharField(max_length=2)),
                ('tipo', models.CharField(choices=[('ausente', 'Dente ausente'), ('implante', 'Implante'), ('endodontia', 'Tratamento endodôntico'), ('restauracao', 'Restauração'), ('coroa', 'Coroa'), ('protese', 'Prótese')], max_length=30)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condicoes_odontologicas', to='accounts.paciente')),
            ],
            options={
                'verbose_name': 'Condição Odontológica',
                'verbose_name_plural': 'Condições Odontológicas',
                'constraints': [models.UniqueConstraint(fields=('paciente', 'dente', 'tipo'), name='unique_condicao_odontologica')],
            },
        ),
    ]
