# Generated by Django 6.0.5 on 2026-09-04 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0117_condicaoodontologica'),
    ]

    operations = [
        migrations.AddField(
            model_name='convenio',
            name='telefone_0800',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='convenio',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
