# Generated by Django 6.0.5 on 2026-09-06 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0118_convenio_telefone_0800_convenio_whatsapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentoclinico',
            name='finalidade_atestado',
            field=models.CharField(blank=True, choices=[('trabalhista', 'Fins trabalhistas'), ('escolar', 'Fins escolares'), ('desportivo', 'Fins desportivos'), ('previdenciario', 'Fins previdenciários'), ('judicial', 'Fins judiciais'), ('militar', 'Fins militares'), ('empresa', 'Apresentação junto a empresa/instituição'), ('outro', 'Outro')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='documentoclinico',
            name='finalidade_atestado_outro',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
