# Generated by Django 6.0.5 on 2026-09-06 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0119_documentoclinico_finalidade_atestado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentoclinico',
            name='finalidade_declaracao',
            field=models.CharField(blank=True, choices=[('trabalhista', 'Fins trabalhistas'), ('escolar', 'Fins escolares'), ('academico', 'Fins acadêmicos'), ('administrativo', 'Fins administrativos'), ('empresa', 'Apresentação junto a empresa/instituição'), ('outro', 'Outro')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='documentoclinico',
            name='finalidade_declaracao_outro',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
