# Generated by Django 6.0.5 on 2026-09-06 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0120_documentoclinico_finalidade_declaracao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentoclinico',
            name='finalidade_atestado',
            field=models.CharField(blank=True, choices=[('trabalhista', 'fins trabalhistas'), ('escolar', 'fins escolares'), ('desportivo', 'fins desportivos'), ('previdenciario', 'fins previdenciários'), ('judicial', 'fins judiciais'), ('militar', 'fins militares'), ('empresa', 'apresentação junto a empresa/instituição'), ('outro', 'outro')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='documentoclinico',
            name='finalidade_declaracao',
            field=models.CharField(blank=True, choices=[('trabalhista', 'fins trabalhistas'), ('escolar', 'fins escolares'), ('academico', 'fins acadêmicos'), ('administrativo', 'fins administrativos'), ('empresa', 'apresentação junto a empresa/instituição'), ('outro', 'outro')], max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='Implantodontia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_procedimento', models.DateField(blank=True, null=True)),
                ('regiao_observacoes', models.TextField(blank=True, null=True)),
                ('observacoes_clinicas', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('dentista_responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='implantodontias_responsavel', to='accounts.perfilusuario')),
                ('documento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='implantodontia', to='accounts.documentoclinico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tratamentos_implantodontia', to='accounts.paciente')),
            ],
            options={
                'verbose_name': 'Implantodontia',
                'verbose_name_plural': 'Implantodontias',
                'ordering': ['-data_procedimento', '-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ImplantodontiaImplante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elemento', models.CharField(max_length=20)),
                ('fabricante', models.CharField(blank=True, max_length=150, null=True)),
                ('modelo_referencia', models.CharField(blank=True, max_length=150, null=True)),
                ('conexao', models.CharField(blank=True, max_length=50, null=True)),
                ('diametro', models.CharField(blank=True, max_length=30, null=True)),
                ('comprimento', models.CharField(blank=True, max_length=30, null=True)),
                ('lote', models.CharField(blank=True, max_length=100, null=True)),
                ('validade', models.DateField(blank=True, null=True)),
                ('registro_anvisa', models.CharField(blank=True, max_length=100, null=True)),
                ('data_instalacao', models.DateField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('implantodontia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='implantes', to='accounts.implantodontia')),
            ],
            options={
                'verbose_name': 'Implante',
                'verbose_name_plural': 'Implantes',
                'ordering': ['elemento', 'id'],
            },
        ),
    ]
