# Generated by Django 6.0.5 on 2026-09-06 22:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0121_alter_documentoclinico_finalidade_atestado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImplantodontiaComponente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('cicatrizador', 'Cicatrizador'), ('pilar', 'Pilar / Abutment'), ('componente_protetico', 'Componente Protético'), ('transferente', 'Transferente'), ('analogo', 'Análogo'), ('outro', 'Outro')], max_length=40)),
                ('fabricante', models.CharField(blank=True, max_length=150, null=True)),
                ('modelo_referencia', models.CharField(blank=True, max_length=150, null=True)),
                ('lote', models.CharField(blank=True, max_length=100, null=True)),
                ('registro_anvisa', models.CharField(blank=True, max_length=100, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('implante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componentes', to='accounts.implantodontiaimplante')),
            ],
            options={
                'verbose_name': 'Componente de Implante',
                'verbose_name_plural': 'Componentes de Implantes',
                'ordering': ['tipo', 'id'],
            },
        ),
    ]
