# Generated by Django 6.0.5 on 2026-09-07 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0122_implantodontiacomponente'),
    ]

    operations = [
        migrations.AddField(
            model_name='implantodontiaimplante',
            name='item_orcamento',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='implante_tecnico', to='accounts.itemorcamento'),
        ),
    ]
