# Generated by Django 6.0.5 on 2026-09-08 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0123_implantodontiaimplante_item_orcamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endodontia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elemento', models.CharField(max_length=20)),
                ('data_procedimento', models.DateField(blank=True, null=True)),
                ('diagnostico_pulpar', models.CharField(blank=True, max_length=150, null=True)),
                ('diagnostico_periapical', models.CharField(blank=True, max_length=150, null=True)),
                ('numero_canais', models.PositiveIntegerField(blank=True, null=True)),
                ('tecnica_material', models.CharField(blank=True, max_length=200, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('dentista_responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='endodontias_responsavel', to='accounts.perfilusuario')),
                ('documento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='endodontia', to='accounts.documentoclinico')),
                ('item_orcamento', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='endodontia_tecnica', to='accounts.itemorcamento')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tratamentos_endodontia', to='accounts.paciente')),
            ],
            options={
                'verbose_name': 'Endodontia',
                'verbose_name_plural': 'Endodontias',
                'ordering': ['-data_procedimento', '-criado_em'],
            },
        ),
    ]
