# Generated by Django 6.0.5 on 2026-09-08 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0124_endodontia'),
    ]

    operations = [
        migrations.AddField(
            model_name='endodontia',
            name='condutometria',
            field=models.TextField(blank=True, null=True),
        ),
    ]
