# Generated by Django 6.0.5 on 2026-09-09 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0125_endodontia_condutometria'),
    ]

    operations = [
        migrations.CreateModel(
            name='Periodontia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elemento', models.CharField(max_length=50)),
                ('data_procedimento', models.DateField(blank=True, null=True)),
                ('diagnostico_periodontal', models.CharField(blank=True, max_length=200, null=True)),
                ('profundidade_sondagem', models.TextField(blank=True, null=True)),
                ('sangramento_sondagem', models.CharField(blank=True, max_length=100, null=True)),
                ('mobilidade', models.CharField(blank=True, max_length=100, null=True)),
                ('recessao_gengival', models.CharField(blank=True, max_length=100, null=True)),
                ('nivel_insercao_clinica', models.CharField(blank=True, max_length=100, null=True)),
                ('procedimento_terapia', models.TextField(blank=True, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('dentista_responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='periodontias_responsavel', to='accounts.perfilusuario')),
                ('documento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='periodontia', to='accounts.documentoclinico')),
                ('item_orcamento', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='periodontia_tecnica', to='accounts.itemorcamento')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tratamentos_periodontia', to='accounts.paciente')),
            ],
            options={
                'verbose_name': 'Periodontia',
                'verbose_name_plural': 'Periodontias',
                'ordering': ['-data_procedimento', '-criado_em'],
            },
        ),
    ]
