# Generated by Django 6.0.5 on 2026-09-10 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0127_fechamentocomissao'),
    ]

    operations = [
        migrations.AddField(
            model_name='contapagar',
            name='fechamento_comissao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comissoes', to='accounts.fechamentocomissao'),
        ),
    ]
