# Generated by Django 6.0.5 on 2026-09-14 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0128_contapagar_fechamento_comissao'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaoclinica',
            name='funciona_domingo',
            field=models.BooleanField(default=False, verbose_name='Domingo'),
        ),
        migrations.AddField(
            model_name='configuracaoclinica',
            name='funciona_quarta',
            field=models.BooleanField(default=True, verbose_name='Quarta-feira'),
        ),
        migrations.AddField(
            model_name='configuracaoclinica',
            name='funciona_quinta',
            field=models.BooleanField(default=True, verbose_name='Quinta-feira'),
        ),
        migrations.AddField(
            model_name='configuracaoclinica',
            name='funciona_sabado',
            field=models.BooleanField(default=False, verbose_name='Sábado'),
        ),
        migrations.AddField(
            model_name='configuracaoclinica',
            name='funciona_segunda',
            field=models.BooleanField(default=True, verbose_name='Segunda-feira'),
        ),
        migrations.AddField(
            model_name='configuracaoclinica',
            name='funciona_sexta',
            field=models.BooleanField(default=True, verbose_name='Sexta-feira'),
        ),
        migrations.AddField(
            model_name='configuracaoclinica',
            name='funciona_terca',
            field=models.BooleanField(default=True, verbose_name='Terça-feira'),
        ),
        migrations.AddField(
            model_name='configuracaoclinica',
            name='hora_fim_agenda',
            field=models.TimeField(default='18:00', verbose_name='Fim do atendimento'),
        ),
        migrations.AddField(
            model_name='configuracaoclinica',
            name='hora_inicio_agenda',
            field=models.TimeField(default='08:00', verbose_name='Início do atendimento'),
        ),
        migrations.AddField(
            model_name='configuracaoclinica',
            name='intervalo_agenda',
            field=models.PositiveIntegerField(choices=[(15, '15 minutos'), (30, '30 minutos'), (60, '60 minutos')], default=30, verbose_name='Intervalo da agenda'),
        ),
    ]
