# Generated by Django 6.0.5 on 2026-09-14 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0129_configuracaoclinica_funciona_domingo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracaoclinica',
            name='hora_fim_almoco',
            field=models.TimeField(default='13:30', verbose_name='Fim do intervalo'),
        ),
        migrations.AddField(
            model_name='configuracaoclinica',
            name='hora_inicio_almoco',
            field=models.TimeField(default='12:00', verbose_name='Início do intervalo'),
        ),
    ]
