# Generated by Django 6.0.5 on 2026-09-17 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0131_consultorio'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedimento',
            name='permite_multiplos_dentes',
            field=models.BooleanField(default=False, verbose_name='Permite seleção múltipla de dentes'),
        ),
    ]
